# Generated by Django 5.2b1 on 2025-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
