# Generated by Django 5.2b1 on 2025-03-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
