# Generated by Django 5.2b1 on 2025-03-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0002_alter_textbook_author_alter_textbook_edition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textbook',
            unique_together={('title', 'author', 'edition', 'condition')},
        ),
    ]
